import { useEffect, useRef, useState } from "react";
import { Canvas, Rect, Circle, Triangle, IText, FabricImage, FabricObject } from "fabric";

export function useDesignEditor() {
  const canvasRef = useRef<HTMLCanvasElement>(null); const fabricRef = useRef<Canvas | null>(null); const containerRef = useRef<HTMLDivElement>(null);
  const [selectedObject, setSelectedObject] = useState<FabricObject | null>(null);
  const [properties, setProperties] = useState({ fill: "#00E5FF", stroke: "#ffffff", strokeWidth: 0, opacity: 1, fontSize: 40, fontFamily: "Inter", fontWeight: "bold" });
  const updatePropertiesFromSelection = () => { const object = fabricRef.current?.getActiveObject(); if (object) setProperties({ fill: (object.fill as string) || "#00E5FF", stroke: (object.stroke as string) || "#ffffff", strokeWidth: object.strokeWidth || 0, opacity: object.opacity || 1, fontSize: (object as any).fontSize || 40, fontFamily: (object as any).fontFamily || "Inter", fontWeight: (object as any).fontWeight || "bold" }); };
  useEffect(() => { if (!canvasRef.current || !containerRef.current) return; const canvas = new Canvas(canvasRef.current, { width: containerRef.current.clientWidth - 40, height: containerRef.current.clientHeight - 80, backgroundColor: "#111111", preserveObjectStacking: true }); fabricRef.current = canvas; canvas.on("selection:created", (event) => setSelectedObject(event.selected?.[0] || null)); canvas.on("selection:updated", (event) => setSelectedObject(event.selected?.[0] || null)); canvas.on("selection:cleared", () => setSelectedObject(null)); canvas.on("object:modified", updatePropertiesFromSelection); const handleResize = () => { if (containerRef.current) { canvas.setDimensions({ width: containerRef.current.clientWidth - 40, height: containerRef.current.clientHeight - 80 }); canvas.renderAll(); } }; window.addEventListener("resize", handleResize); return () => { window.removeEventListener("resize", handleResize); canvas.dispose(); }; }, []);
  const addObject = (object: FabricObject) => { fabricRef.current?.add(object); fabricRef.current?.setActiveObject(object); fabricRef.current?.renderAll(); };
  const addRect = () => addObject(new Rect({ left: 100, top: 100, fill: properties.fill, width: 100, height: 100, stroke: "#ffffff", strokeWidth: 0 }));
  const addCircle = () => addObject(new Circle({ left: 100, top: 100, fill: properties.fill, radius: 50, stroke: "#ffffff", strokeWidth: 0 }));
  const addTriangle = () => addObject(new Triangle({ left: 100, top: 100, fill: properties.fill, width: 100, height: 100, stroke: "#ffffff", strokeWidth: 0 }));
  const addText = () => addObject(new IText("TEXTO AQUI", { left: 100, top: 100, fontFamily: "Inter", fontWeight: "900", fontSize: 40, fill: properties.fill }));
  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = async (loadEvent) => { if (typeof loadEvent.target?.result === "string") { const image = await FabricImage.fromURL(loadEvent.target.result); image.scale(0.5); fabricRef.current?.add(image); fabricRef.current?.centerObject(image); fabricRef.current?.setActiveObject(image); fabricRef.current?.renderAll(); } }; reader.readAsDataURL(file); };
  const withActiveObject = (action: (object: FabricObject) => void) => { const object = fabricRef.current?.getActiveObject(); if (object) { action(object); fabricRef.current?.renderAll(); } };
  const deleteObject = () => { const objects = fabricRef.current?.getActiveObjects(); if (objects) { fabricRef.current?.discardActiveObject(); objects.forEach((object) => fabricRef.current?.remove(object)); fabricRef.current?.renderAll(); } };
  const bringForward = () => withActiveObject((object) => fabricRef.current?.bringObjectForward(object)); const sendBackwards = () => withActiveObject((object) => fabricRef.current?.sendObjectBackwards(object)); const bringToFront = () => withActiveObject((object) => fabricRef.current?.bringObjectToFront(object)); const sendToBack = () => withActiveObject((object) => fabricRef.current?.sendObjectToBack(object));
  const handlePropertyChange = (key: string, value: any) => { setProperties((previous) => ({ ...previous, [key]: value })); const object = fabricRef.current?.getActiveObject(); if (object) { object.set(key as any, value); fabricRef.current?.renderAll(); } };
  const exportSVG = () => { if (!fabricRef.current) return; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([fabricRef.current.toSVG()], { type: "image/svg+xml" })); link.download = "design-export.svg"; link.click(); };
  const exportPNG = () => { if (!fabricRef.current) return; const link = document.createElement("a"); link.href = fabricRef.current.toDataURL({ format: "png", multiplier: 2 }); link.download = "design-export.png"; link.click(); };
  return { canvasRef, containerRef, selectedObject, properties, addRect, addCircle, addTriangle, addText, handleImageUpload, deleteObject, bringForward, sendBackwards, bringToFront, sendToBack, handlePropertyChange, exportSVG, exportPNG };
}
