import type { FastenerConfig, FastenerSizeSpec } from "./types";
import { resolveHeadDims, resolveNutDims, resolveWasherDims } from "./sizes";
import { threadDepth } from "./threads";

/**
 * Renders a fastener as self-contained pure OpenSCAD (no BOSL2). Threads are
 * built by stacking `linear_extrude(twist=360)` teeth per pitch, so it
 * renders with any installed OpenSCAD. All numeric values are interpolated
 * from the ISO/UTS size tables — never `${...}` literals.
 */
export function generateScad(config: FastenerConfig, spec: FastenerSizeSpec): string {
  const num = (v: number) => String(Math.round(v * 1000) / 1000);
  const lines: string[] = [];

  lines.push("// Generated by 3dlabOpen Screw Generator", "// Pure OpenSCAD - no external libraries required", "$fn = 64;", "");

  // Shared modules --------------------------------------------------------
  lines.push(
    "module thread_ridge(r, pitch) {",
    "    h = pitch * 0.42;",
    "    w = pitch * 0.55;",
    "    translate([r - h, -w / 2]) square([h, w]);",
    "}",
    "",
    "module thread_rod(d, pitch, length) {",
    "    r = d / 2;",
    "    teeth = ceil(length / pitch);",
    "    for (i = [0 : teeth - 1]) {",
    "        translate([0, 0, i * pitch])",
    "        linear_extrude(height = pitch, twist = 360, slices = 48, convexity = 4)",
    "        thread_ridge(r, pitch);",
    "    }",
    "}",
    "",
    "module chamfer_ring(r, h, z) {",
    "    ch = 0.4;",
    "    difference() {",
    "        translate([0, 0, z - ch]) cylinder(h = 2 * ch, r1 = r, r2 = 0.01, $fn = 64);",
    "        translate([0, 0, z - ch - 0.01]) cylinder(h = 2 * ch + 0.02, r = r - 0.5, $fn = 64);",
    "    }",
    "}",
    ""
  );

  if (config.type === "screw") {
    emitScrew(lines, config, spec, num);
  } else if (config.type === "nut") {
    emitNut(lines, config, spec, num);
  } else {
    emitWasher(lines, config, spec, num);
  }

  if (config.debugMode) {
    lines.push(`echo("size=${config.size} type=${config.type}");`);
  }

  return lines.join("\n");
}

function emitScrew(
  lines: string[],
  config: FastenerConfig,
  spec: FastenerSizeSpec,
  num: (v: number) => string
): void {
  const major = spec.majorD;
  const pitch = spec.pitch;
  const length = Math.max(1, config.length);
  const fullThread = config.fullThread;
  const threadLen = fullThread ? length : Math.min(Math.max(1, config.threadLength), length);
  const EPS = 0.02;
  const head = resolveHeadDims(spec, config.headType);
  const dk = head.dk;
  const k = head.k;

  const depth = threadDepth(pitch);
  const headTop = length + k;
  const recessD = Math.max((head.socket ?? Math.max(0.8, major * 0.8)) * 1.15, 0.8);
  const recessDepth = k + 1.0;

  lines.push("module screw() {");
  lines.push(`    L = ${num(length)};`);
  lines.push(`    D = ${num(major + EPS)};`);
  lines.push(`    P = ${num(pitch)};`);
  lines.push(`    threadEnd = ${num(threadLen + pitch)};`);
  lines.push(`    shankEnd = ${num(length)};`);
  lines.push(`    dk = ${num(dk)};`);
  lines.push(`    k = ${num(k)};`);
  lines.push(`    r = D / 2;`);
  lines.push("");
  lines.push("    // 1. Threaded rod (extends one pitch into the head for a clean join)");
  lines.push("    thread_rod(D, P, threadEnd);");
  lines.push("");
  if (!fullThread && threadLen < length) {
    lines.push(`    // 2. Plain shank for partial-thread screws`);
    lines.push(`    translate([0, 0, threadEnd]) cylinder(h = max(shankEnd - threadEnd, 0.001), r = r, $fn = 64);`);
  }
  lines.push("");
  lines.push("    // 3. Head");
  const headBlock = headShapeBlock(config.headType, head);
  lines.push("    translate([0, 0, L]) {");
  for (const l of headBlock) lines.push(`        ${l}`);
  lines.push("    }");
  lines.push("");

  // 4. Drive recess
  const cutters = driveCuttersBlock(config.driveType, head, major, recessD, recessDepth);
  if (cutters.length > 0) {
    lines.push("    // 4. Drive recess");
    lines.push("    difference() {");
    lines.push("        children();");
    lines.push("        translate([0, 0, headTop - recessDepth / 2]) {");
    for (const c of cutters) lines.push(`            ${c}`);
    lines.push("        }");
    lines.push("    }");
  }
  lines.push("}");
  lines.push("");
  lines.push(`headTop = ${num(headTop)};`);
  lines.push(`recessDepth = ${num(recessDepth)};`);
  lines.push("");

  let call = "screw();";
  if (config.splitScrew) {
    call = "intersection() {\n    screw();\n    translate([0, -500, -500]) cube([500, 1000, 1000]);\n}";
  }
  lines.push(call);
}

function headShapeBlock(headType: FastenerConfig["headType"], head: { dk: number; k: number }): string[] {
  const dk = head.dk;
  const k = head.k;
  switch (headType) {
    case "hex":
      return [`cylinder(h = k, r = dk / 2, $fn = 6);`];
    case "flat":
      return [`cylinder(h = k, r1 = dk / 2, r2 = 0.01, $fn = 64);`];
    case "button":
      return [
        `cylinder(h = k, r = dk / 2, $fn = 64);`,
        `translate([0, 0, k]) sphere(r = dk / 2, $fn = 64);`,
      ];
    case "pan":
      return [`cylinder(h = k, r1 = dk / 2, r2 = dk * 0.85 / 2, $fn = 64);`];
    case "socket":
    case "ribbed_socket":
    default:
      return [`cylinder(h = k, r = dk / 2, $fn = 64);`];
  }
}

function driveCuttersBlock(
  driveType: FastenerConfig["driveType"],
  head: { socket?: number },
  major: number,
  recessD: number,
  recessDepth: number
): string[] {
  switch (driveType) {
    case "hex":
      return [`cylinder(h = recessDepth + 0.02, r = recessD / 2, $fn = 6, center = true);`];
    case "slot":
      return [`cube([recessD * 2.4, recessD * 0.32, recessDepth + 0.02], center = true);`];
    case "phillips":
      return [
        `cube([recessD * 2.2, recessD * 0.42, recessDepth + 0.02], center = true);`,
        `cube([recessD * 0.42, recessD * 2.2, recessDepth + 0.02], center = true);`,
      ];
    case "torx": {
      const pts: string[] = [];
      for (let i = 0; i < 12; i++) {
        const r = i % 2 === 0 ? recessD * 0.55 : recessD * 0.34;
        const a = (i / 12) * Math.PI * 2 - Math.PI / 2;
        pts.push(`[${(Math.cos(a) * r).toFixed(4)}, ${(Math.sin(a) * r).toFixed(4)}]`);
      }
      return [
        `linear_extrude(height = recessDepth + 0.02, center = true, $fn = 64)`,
        `    polygon(points = [${pts.join(", ")}]);`,
      ];
    }
    default:
      return [];
  }
}

function emitNut(lines: string[], config: FastenerConfig, spec: FastenerSizeSpec, num: (v: number) => string): void {
  const thickness = config.nutThicknessOverride > 0 ? config.nutThicknessOverride : resolveNutDims(spec, config.nutShape).m;
  const s = resolveNutDims(spec, config.nutShape).s;
  const major = spec.majorD;
  const pitch = spec.pitch;
  const clearance = config.clearance;
  const depth = threadDepth(pitch);
  const holeD = major + clearance;
  const circum = s / (2 * Math.cos(Math.PI / 6));

  lines.push("module nut() {");
  lines.push(`    t = ${num(thickness)};`);
  lines.push(`    s = ${num(s)};`);
  lines.push(`    holeD = ${num(holeD)};`);
  lines.push(`    P = ${num(pitch)};`);
  lines.push(`    depth = ${num(depth)};`);
  lines.push(`    r = ${num(circum)};`);
  lines.push("");
  lines.push("    difference() {");
  lines.push("        // Body");
  if (config.nutShape === "hex") {
    lines.push("        translate([0, 0, -t / 2]) cylinder(h = t, r = r, $fn = 6);");
  } else {
    lines.push("        translate([0, 0, -t / 2]) cube([s, s, t], center = true);");
  }
  lines.push("        // Threaded hole (one pitch past each face)");
  lines.push(`        translate([0, 0, -t / 2 - P]) thread_rod(holeD + 2 * depth, P, t + 2 * P);`);
  if (config.bevelNut) {
    lines.push("        // Edge chamfers");
    lines.push("        chamfer_ring(r, t, -t / 2);");
    lines.push("        chamfer_ring(r, t, t / 2);");
  }
  lines.push("    }");
  lines.push("}");
  lines.push("");
  lines.push("nut();");
}

function emitWasher(
  lines: string[],
  config: FastenerConfig,
  spec: FastenerSizeSpec,
  num: (v: number) => string
): void {
  if (config.washerType === "spring") {
    emitSpringWasher(lines, config, spec, num);
    return;
  }

  const w = resolveWasherDims(spec, config.washerType === "large");
  const d1 = w.d1;
  const d2 = w.d2;
  const h = w.h;

  lines.push("module washer() {");
  lines.push(`    d1 = ${num(d1)};`);
  lines.push(`    d2 = ${num(d2)};`);
  lines.push(`    h = ${num(h)};`);
  lines.push("");
  lines.push("    difference() {");
  lines.push("        cylinder(h = h, r = d2 / 2, $fn = 64);");
  lines.push("        cylinder(h = h + 0.02, r = d1 / 2, $fn = 64, center = true);");
  if (config.washerChamfer) {
    lines.push("        chamfer_ring(d2 / 2, h, 0);");
    lines.push("        chamfer_ring(d2 / 2, h, h);");
  }
  lines.push("    }");
  lines.push("}");
  lines.push("");
  lines.push("washer();");
}

/** Helical spring lock washer (DIN 127): split ring approximated by stacked
 *  angled band segments so it renders in pure OpenSCAD. */
function emitSpringWasher(
  lines: string[],
  _config: FastenerConfig,
  spec: FastenerSizeSpec,
  num: (v: number) => string
): void {
  const w = resolveWasherDims(spec, false);
  const d1 = w.d1;
  const d2 = w.d2;
  const b = (d2 - d1) / 2;
  const s = Math.max(0.4, b * 0.6);
  const H = 2 * s;
  const rm = (d1 + d2) / 4;
  const gapDeg = Math.max(8, (2 * Math.max(0.4, s * 0.6) / rm) * 180 / Math.PI);
  const N = 96;

  lines.push("module spring_washer() {");
  lines.push(`    d1 = ${num(d1)};`);
  lines.push(`    d2 = ${num(d2)};`);
  lines.push(`    b = ${num(b)};`);
  lines.push(`    s = ${num(s)};`);
  lines.push(`    H = ${num(H)};`);
  lines.push(`    rm = ${num(rm)};`);
  lines.push(`    N = ${N};`);
  lines.push(`    step = (360 - ${num(gapDeg)}) / N;`);
  lines.push("    for (i = [0 : N - 1]) {");
  lines.push("        a = i * step;");
  lines.push("        z = (i / N) * (H - s);");
  lines.push("        rotate([0, 0, a])");
  lines.push("        translate([rm, 0, z])");
  lines.push("        cube([b, rm * step * PI / 180 + 0.4, s], center = true);");
  lines.push("    }");
  lines.push("}");
  lines.push("");
  lines.push("spring_washer();");
}